### ISSUE TITLE
Improve links to papers in readme

### ISSUE THREAD

**Issue by impredicative** [iVMCL/AOGNets#2]
About the link to the AOGNets paper in the readme, it currently points to the PDF version. It would be better if it were to point to the HTML version instead, i.e. https://arxiv.org/abs/1711.05847 . Please consider making this change. Readers can always click on the PDF link themselves.

Secondly, the link to "Mixture Normalization: A Lightweight Integration of Feature Normalization and Attention" is broken. What should it be pointing to?

**Comment by iVMCL** [comment]
Thank you very much. We will update those. The second link will be available soon (we are revising the paper and will upload it to arXiv). Thanks.
